language: swift
os: osx
osx_image: xcode10

cache:
  directories:
  - Carthage

install:
  - carthage bootstrap --no-use-binaries --platform iOS --cache-builds

script: 
  - xcodebuild clean
  - xcodebuild test -project Budgetee.xcodeproj -scheme Budgetee -destination 'platform=iOS Simulator,name=iPhone X'