language: swift
os: osx
osx_image: xcode9.3

cache:
  directories:
  - Carthage

install:
  - carthage bootstrap --no-use-binaries --platform iOS --cache-builds

script: 
  - xcodebuild clean build -sdk iphonesimulator -project Budgetee.xcodeproj -scheme Budgetee CODE_SIGNING_REQUIRED=NO
