language: swift
os: osx
osx_image: xcode9.3
xcode_project: Budgetee.xcodeproj
xcode_scheme: Budgetee

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --no-use-binaries --platform iOS --cache-builds


script: 
  - xcodebuild clean build -sdk iphonesimulator -project Budgetee.xcodeproj -scheme Budgetee CODE_SIGNING_REQUIRED=NO
  